services:
  nginx:
    image: nginx:latest
    container_name: nginx_ssl
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  netshoot:
    image: nicolaka/netshoot
    container_name: netshoot
    command: sleep infinity
    volumes:
      - ./certs:/root/certs
    depends_on:
      - nginx
